Fix misspelled words, Improve chat title bar
DIBgram/DIBgram pull request #6
Opened 2021-11-16 11:28 UTC by Muaath5

**What new features or bug fixes does this pull request introduce? Explain.**
- Chat title bar
- Fix misspelled file names & icons

**Is this pull request related to an existing issue?**
Probably

**Does this pull request comply with the conditions described in contribution [guidelines](https://github.com/DIBgram/DIBgram/blob/main/CONTRIBUTING.md#submitting-a-pull-request)?**

- [x] There are no errors, warnings or notices from ESLint or StyleLint
- [x] It compiles and runs successfully
- [x] It does not introduce a feature that is not present in the official Telegram Desktop app
- [x] Behavior and UI is similar to the official Telegram Desktop app

2021-11-16 11:38 UTC, Mammad900 requested changes
I've found some errors in your pull request. Please check them.

2021-11-16 11:38 UTC, Mammad900 commented on src/dibgram/messenger/sections/chat/headers/title.scss
> +        flex-grow: 1;
Why `flex-grow: 1;`?

2021-11-16 11:38 UTC, Mammad900 commented on src/dibgram/messenger/sections/chat/headers/title.scss
> +        align-items: flex-end;
Are you sure a flexbox is needed here?

2021-11-16 11:38 UTC, Mammad900 commented on src/dibgram/messenger/sections/chat/headers/title.js
> +                    {(chat.type['@type'] == 'chatTypeBasicGroup' || (chat.type['@type'] == 'chatTypeSupergroup' && !chat.type.is_channel)) && __pl('lng_chat_status_members', 5)}
Not all groups or channels have 5 members.

2021-11-16 11:38 UTC, Mammad900 commented on src/dibgram/messenger/sections/chat/headers/title.js
> +                        <Menu.MenuItem>{chat.can_be_reported && __('lng_report_button')}</Menu.MenuItem>
The condition should be outside the menu item.

2021-11-16 12:17 UTC, Muaath5 commented on src/dibgram/messenger/sections/chat/headers/title.scss
> +        align-items: flex-end;
I don't know how to place it in the right place unless this way.

2021-11-16 12:29 UTC, Mammad900 commented
```
Failed to compile.

./src/dibgram/messenger/sections/settings/choose-lanugage.js
Error: ENOENT: no such file or directory, open '[redacted]\src\dibgram\messenger\sections\settings\choose-lanugage.js'  
```
You renamed the file but did not fix the imports

2021-11-16 12:34 UTC, Mammad900 commented on src/dibgram/messenger/sections/chat/headers/title.js
> +                        <Menu.MenuItem>{chat.can_be_reported && __('lng_report_button')}</Menu.MenuItem>
![image](https://user-images.githubusercontent.com/67197540/141986072-edb8fa3f-3326-4f07-b5e6-0e38656385e2.png)
This is what happens when a chat isn't reportable

2021-11-16 12:43 UTC, Mammad900 commented on src/dibgram/messenger/sections/chat/headers/title.scss
> +        align-items: flex-end;
```suggestion
        flex-shrink: 0;

        & > .three-dots-menu,
        & > .icon-button {
            float: unset;
            margin: 7px;
        }
```

2021-11-16 12:45 UTC, Mammad900 commented on src/dibgram/messenger/sections/chat/headers/title.js
> +                        <Menu.MenuItem>{chat.can_be_reported && __('lng_report_button')}</Menu.MenuItem>
```suggestion
                        {chat.can_be_reported && <Menu.MenuItem>{__('lng_report_button')}</Menu.MenuItem>}
```

2021-11-16 12:48 UTC, Muaath5 commented
@Mammad900 I forgot to do Ctrl+S XD

2021-11-16 12:48 UTC, Mammad900 commented
@Muaath5 Don't worry, I fixed it for you.

2021-11-17 15:35 UTC, Mammad900 commented on src/dibgram/messenger/sections/chat/headers/title.scss
> +        }
```suggestion
        .info {
            margin-top: 2px;
            font-size: 13px;
            font-weight: 400;
            color: var(--theme-color-windowSubTextFg);
        }
```

2021-11-17 19:44 UTC, Mammad900 approved these changes

2021-11-17 19:47 UTC, merged